app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

  tags-filter-regex: "[\\w]{1,}"
  update-delay: 3600000 # milliseconds

  bot-url: http://localhost:8080
  github-api-url: https://api.github.com
  stackoverflow-api-url: https://api.stackexchange.com/2.2

  enable-kafka: true
  access-type: orm # sql, orm
  message-transport: kafka # kafka, http

  update-threads-cnt: 10
  update-thread-batch-size: 100

  kafka-topics:
    updates: updates
    dead-letters-queue: dead-letters

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      kafka-notification-sender:
        base-config: default
      http-notification-sender:
        base-config: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
    instances:
      kafka-notification-sender:
        base-config: default
      http-notification-sender:
        base-config: default
  timelimiter:
    configs:
      client-default:
        timeout-duration: 2s
      controller-default:
        timeout-duration: 2s
    instances:
      kafka-notification-sender:
        base-config: client-default
      http-notification-sender:
        base-config: client-default
      notifications-controller:
        base-config: controller-default
      chat-controller:
        base-config: controller-default
      links-controller:
        base-config: controller-default
      tags-controller:
        base-config: controller-default
  ratelimiter:
    configs:
      controller-default:
        limit-for-period: 20
        limit-refresh-period: 1s
    instances:
      notifications-controller:
        base-config: controller-default
      chat-controller:
        base-config: controller-default
      links-controller:
        base-config: controller-default
      tags-controller:
        base-config: controller-default

spring:
  profiles:
    default: prod
  application:
    name: Scrapper

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/scrapper
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  kafka:
    bootstrap-servers: localhost:19092
    consumer.properties:
      enable.auto.commit: false
      auto.offset.reset: earliest
      isolation.level: read_committed
      fetch.min.bytes: 1024
      fetch.max.bytes: 1048576
      fetch.max.wait.ms: 10000
      max.poll.interval.ms: 10000
      max.poll.records: 10
#      schema.registry.url: http://localhost:8083
  cloud.zookeeper:
    config.enabled: false
    connect-string: localhost:2181
  data:
    redis:
      host: localhost
      port: 6379


logging:
  structured:
    format:
      console: ecs
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    root: info


server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
debug:
