app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

  tags-filter-regex: "[\\w]{1,}"
  update-delay: 3600000 # milliseconds

  bot-url: http://localhost:8080

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tbhw
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG


server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
