app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

  tags-filter-regex: "[\\w]{1,}"
  update-delay: 3600000 # milliseconds

  bot-url: http://localhost:8080
  github-api-url: https://api.github.com
  stackoverflow-api-url: https://api.stackexchange.com/2.2
  db-access-impl: orm # sql or orm



spring:
  profiles:
    default: prod
  application:
    name: Scrapper

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/tbhw
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}


logging:
  structured:
    format:
      console: ecs
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG


server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
