app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tbhw
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
