app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: 'http://localhost:8081'
  url-regex: "^(https?:\\/\\/)?(?:www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b(?:[-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)$"

spring:
  profiles:
    default: prod
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  structured:
    format:
      console: ecs

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
